<?php

namespace AppBundle\Repository;

/**
 * AbilityEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbilityEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
