<?php

namespace AppBundle\Repository;

/**
 * BattlefieldRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattlefieldRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
