<?php

namespace AppBundle\Repository;

/**
 * MountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MountRepository extends \Doctrine\ORM\EntityRepository
{
}
