<?php

namespace AppBundle\Repository;

/**
 * pitchedBattleRuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PitchedBattleRuleRepository extends \Doctrine\ORM\EntityRepository
{
}
