<?php

namespace AppBundle\Repository;

/**
 * PitchedBattleRuleEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PitchedBattleRuleEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
