<?php

namespace AppBundle\Repository;

/**
 * SpellEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpellEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
