<?php

namespace AppBundle\Repository;

/**
 * SpellRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpellRepository extends \Doctrine\ORM\EntityRepository
{
}
