<?php

namespace AppBundle\Repository;

/**
 * UnitAbilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitAbilityRepository extends \Doctrine\ORM\EntityRepository
{
}
