<?php

namespace AppBundle\Repository;

/**
 * WarscrollBattalionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarscrollBattalionRepository extends \Doctrine\ORM\EntityRepository
{
}
